[character]
	success_symbol = "[➜](bold blue) "
	error_symbol = "[✗](bold red) "
[package]
	disabled = true
[nodejs]
	disabled = true
[time]
	disabled = false
	format =  '[\[ $time \]]($style) '
	time_format = "%T"
	# utc_time_offset = "-5"
	time_range = "10:00:00-14:00:00"
